apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: srishtirupa/flaskweb:latest
        ports:
        - containerPort: 8000